### ISSUE TITLE
how to add some animation on APAlertView when present & dismiss

### ISSUE THREAD

**Issue by shywoody** [Arvindcs/APAlertView#2]

**Comment by Arvindcs** [comment]
Hi hywoody,

Thanks for raising an issue.
I have added animation and updated the repository. thanks

**Comment by shywoody** [comment]
> Hi hywoody,
> 
> Thanks for raising an issue. I have added animation and updated the repository. thanks

thx, that's very kind of you😆. i noice that toast have many solutions.like Zstack.. overlay...present a UIHostingController on current window's rootController by system...&yours.which way is better？😢.  I have a vague feeling that `makeKeyAndVisible()` is not very stable. but it's very smart idear
